import type { CampaignData } from "../components/Dashboard";

export const dummyData: CampaignData[] = [
  {
    date: '22-Sep-25',
    week: 'Week 38',
    editor: 'John Doe',
    painPoint: 'Lead Generation',
    product: 'SaaS Tool A',
    production: 'Video',
    adType: 'Conversion',
    format: 'Single Image',
    landingPage: 'LP-001',
    totalAssets: 2,
    hits: 0,
    week1: 0.0,
    week2: 0.0,
    week3: 0.0,
    week4: 0.0
  },
  {
    date: '15-Sep-25',
    week: 'Week 37',
    editor: 'Jane Smith',
    painPoint: 'Brand Awareness',
    product: 'SaaS Tool B',
    production: 'Static',
    adType: 'Traffic',
    format: 'Carousel',
    landingPage: 'LP-002',
    totalAssets: 271,
    hits: 91,
    week1: 33.6,
    week2: 33.6,
    week3: 33.6,
    week4: 33.6
  },
  {
    date: '08-Sep-25',
    week: 'Week 36',
    editor: 'Mike Johnson',
    painPoint: 'Lead Generation',
    product: 'SaaS Tool A',
    production: 'Video',
    adType: 'Lead Generation',
    format: 'Single Image',
    landingPage: 'LP-001',
    totalAssets: 64,
    hits: 30,
    week1: 46.9,
    week2: 56.3,
    week3: 56.3,
    week4: 56.3
  },
  {
    date: '01-Sep-25',
    week: 'Week 35',
    editor: 'Sarah Wilson',
    painPoint: 'Customer Retention',
    product: 'SaaS Tool C',
    production: 'Static',
    adType: 'Conversion',
    format: 'Video',
    landingPage: 'LP-003',
    totalAssets: 353,
    hits: 23,
    week1: 6.5,
    week2: 11.9,
    week3: 11.9,
    week4: 11.9
  },
  {
    date: '25-Aug-25',
    week: 'Week 34',
    editor: 'John Doe',
    painPoint: 'Lead Generation',
    product: 'SaaS Tool B',
    production: 'Video',
    adType: 'Conversion',
    format: 'Carousel',
    landingPage: 'LP-002',
    totalAssets: 550,
    hits: 53,
    week1: 9.6,
    week2: 25.9,
    week3: 30.7,
    week4: 33.7
  },
  {
    date: '18-Aug-25',
    week: 'Week 33',
    editor: 'Jane Smith',
    painPoint: 'Brand Awareness',
    product: 'SaaS Tool A',
    production: 'Static',
    adType: 'Traffic',
    format: 'Single Image',
    landingPage: 'LP-001',
    totalAssets: 333,
    hits: 24,
    week1: 7.3,
    week2: 12.9,
    week3: 12.9,
    week4: 16.2
  },
  {
    date: '11-Aug-25',
    week: 'Week 32',
    editor: 'Mike Johnson',
    painPoint: 'Customer Retention',
    product: 'SaaS Tool C',
    production: 'Video',
    adType: 'Lead Generation',
    format: 'Video',
    landingPage: 'LP-003',
    totalAssets: 309,
    hits: 15,
    week1: 5.0,
    week2: 7.1,
    week3: 7.1,
    week4: 7.1
  },
  {
    date: '04-Aug-25',
    week: 'Week 31',
    editor: 'Sarah Wilson',
    painPoint: 'Lead Generation',
    product: 'SaaS Tool B',
    production: 'Static',
    adType: 'Conversion',
    format: 'Carousel',
    landingPage: 'LP-002',
    totalAssets: 390,
    hits: 7,
    week1: 1.8,
    week2: 21.3,
    week3: 25.6,
    week4: 25.6
  },
  {
    date: '28-Jul-25',
    week: 'Week 30',
    editor: 'John Doe',
    painPoint: 'Brand Awareness',
    product: 'SaaS Tool A',
    production: 'Video',
    adType: 'Traffic',
    format: 'Single Image',
    landingPage: 'LP-001',
    totalAssets: 249,
    hits: 5,
    week1: 1.2,
    week2: 3.2,
    week3: 3.2,
    week4: 3.2
  },
  {
    date: '21-Jul-25',
    week: 'Week 29',
    editor: 'Jane Smith',
    painPoint: 'Customer Retention',
    product: 'SaaS Tool C',
    production: 'Static',
    adType: 'Lead Generation',
    format: 'Video',
    landingPage: 'LP-003',
    totalAssets: 206,
    hits: 3,
    week1: 1.7,
    week2: 5.7,
    week3: 5.7,
    week4: 6.5
  },
  {
    date: '14-Jul-25',
    week: 'Week 28',
    editor: 'Mike Johnson',
    painPoint: 'Lead Generation',
    product: 'SaaS Tool A',
    production: 'Video',
    adType: 'Conversion',
    format: 'Single Image',
    landingPage: 'LP-001',
    totalAssets: 360,
    hits: 30,
    week1: 8.5,
    week2: 8.3,
    week3: 8.3,
    week4: 8.3
  },
  {
    date: '07-Jul-25',
    week: 'Week 27',
    editor: 'Sarah Wilson',
    painPoint: 'Brand Awareness',
    product: 'SaaS Tool B',
    production: 'Static',
    adType: 'Traffic',
    format: 'Carousel',
    landingPage: 'LP-002',
    totalAssets: 541,
    hits: 32,
    week1: 5.9,
    week2: 6.8,
    week3: 7.0,
    week4: 7.0
  }
];